name: $(Date:yyyyMMdd).$(Rev:r)

variables:
  DGSIP.Solution: 'ALPHA.sln'
  DGSIP.BuildPlatform: 'Any CPU'
  DGSIP.BuildConfiguration: 'Release'

trigger:
- main 
pool:
  name: DGS Local
  
jobs:
- job: Build
  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: 'Install dotnet SDK 6.0.x'
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(DGSIP.BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish zip as artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'isa-magazijn-$(Build.BuildNumber)'
      publishLocation: 'Container'